### ISSUE TITLE
Reuse a single dialog component

### ISSUE THREAD

**Issue by brianreinhold** [johnbwoodruff/johnbwoodruff-blog#1]
Great article on the Angular CDK custom dialog. RIght now I am not using the custom approach but have to use the material theme, even though the CDK/dialog is the only import I am using.

However, I have many many dialog entries that I need and it looks like you need to have a component for every dialog. I have one component with a generic interface with almost all fields optionals. What I end up doing when I need a popup is to pass the data to this single dialog component and it displays the defined fields of the interface.

I would like to do the same thing using your approach so I have full control of the styling but I am not sure how that could be done. Perhaps by changing your dialog service to a component with an html that displays the defined fields of the data interface?

I dont want to create a component for every dialog that I need to popup. That would create a huge number of components with html, css, and ts files that are very similar.

**Comment by johnbwoodruff** [comment]
Hi @brianreinhold I'm glad you enjoyed the post! This is the first time I've gotten a GitHub issue as a comment on one of my blog posts haha. As for your question, absolutely my post is about the reusability of the dialog service that allows you to open whatever component you want in a dialog. You could absolutely just use a single component that has a defined interface and you pass that data through the open method. Totally up to you. :)

**Comment by brianreinhold** [comment]
I should have mentioned that it wasn't an 'issue' but I saw no other way to pose this question or respond to the blog. I think what I can do is pass the current dialog component I have now with my generic structure html page to your service and have the other components that use the dialog call my dialog component as usual, passing the data structure and resolving the Observable. Something like that. But I do want to get rid of all that angular material theme baggage!

**Comment by johnbwoodruff** [comment]
Yeah basically just instead of passing a component to the open method you would instead pass whatever your config object is, and then the component you use is just a custom component you build that is defined in the service itself rather than provided by the implementer. That's one way you could do it anyway.
